name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/generated/github-snake.svg?color_snake=#E6EDF3&color_dots=#161B22,#2A2A2A,#405056,#618A96,#BDEEFF
            assets/generated/github-snake-dark.svg?color_snake=#E6EDF3&color_dots=#161B22,#2A2A2A,#405056,#618A96,#BDEEFF&palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/generated/github-snake.svg assets/generated/github-snake-dark.svg
          git commit -m "chore: update contribution snake [skip ci]" || exit 0
          git push
